import type { Metadata } from "next";
import { Geist, Geist_Mono, Quicksand } from "next/font/google";
import "./globals.css";
// import { ApolloProvider } from "@apollo/client";
// import { getClient } from "@/lib/apollo";
// import QueryProvider from "@/components/QueryProvider";
// import { Session } from "inspector/promises";
// import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
// ("@/lib/apollo");

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const quickSand = Quicksand({
  variable: "--font-quick-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const dynamic = "error";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quickSand.variable} ${quickSand.variable} antialiased bg-[#E0E0E0] dark:bg-[#FAF9F6] text-black dark:text-white`}
      >
        {/* <ApolloProvider client={getClient}> */}
        {/* <SessionProvider> */}
        <Navbar />
        <div className="mt-20"></div>
        {/* <QueryProvider> */}
        {children}

        {/* </QueryProvider> */}
        {/* </SessionProvider> */}

        {/* </ApolloProvider> */}
        <Footer />
      </body>
    </html>
  );
}
